# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lord_config = debug
endif
ifeq ($(config),release)
  lord_config = release
endif

PROJECTS := lord

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lord:
ifneq (,$(lord_config))
	@echo "==== Building lord ($(lord_config)) ===="
	@${MAKE} --no-print-directory -C lord -f Makefile config=$(lord_config)
endif

clean:
	@${MAKE} --no-print-directory -C lord -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lord"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"