AST:
	%r0(0) MODULE '' 0..0
		%r0(0) FN 'test_add_sub' 9..21
			%r0(0) ARGS '' 0..0
			%r0(4) SUB '-' 31..32
				%r0(4) ADD '+' 27..28
					%r0(4) INT '1' 25..26
					%r1(4) INT '2' 29..30
				%r1(4) INT '3' 33..34
		%r0(0) FN 'test_mul_div_mod' 36..52
			%r0(0) ARGS '' 0..0
			%r0(4) MOD '%' 67..68
				%r0(4) DDIV '//' 62..64
					%r0(4) MUL '*' 58..59
						%r0(4) INT '1' 56..57
						%r1(4) INT '2' 60..61
					%r1(4) INT '3' 65..66
				%r1(4) INT '4' 69..70
		%r0(0) FN 'test_mul_div_mod_2' 72..90
			%r0(0) ARGS '' 0..0
			%r0(4) MOD '%' 107..108
				%r0(4) MUL '*' 96..97
					%r0(4) INT '1' 94..95
					%r1(4) DDIV '//' 101..103
						%r1(4) INT '2' 99..100
						%r2(4) INT '3' 104..105
				%r1(4) INT '4' 109..110
		%r0(0) FN 'test_all' 112..120
			%r0(0) ARGS '' 0..0
			%r0(4) SUB '-' 130..131
				%r0(4) ADD '+' 126..127
					%r0(4) INT '1' 124..125
					%r1(4) INT '2' 128..129
				%r1(4) MOD '%' 143..144
					%r1(4) DDIV '//' 138..140
						%r1(4) MUL '*' 134..135
							%r1(4) INT '3' 132..133
							%r2(4) INT '4' 136..137
						%r2(4) INT '5' 141..142
					%r2(4) INT '6' 145..146

FNS:
	test_add_sub:
		type:
			%r0(4) INT 'Int' 0..0
		args:
	test_all:
		type:
			%r0(4) INT 'Int' 0..0
		args:
	test_mul_div_mod:
		type:
			%r0(0) NONE '' 0..0
		args:
	test_mul_div_mod_2:
		type:
			%r0(0) NONE '' 0..0
		args:
